# Generated by Django 5.0.7 on 2024-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=50)),
                ('assignment_type', models.CharField(max_length=10)),
                ('assignment_status', models.CharField(max_length=10)),
                ('creation_date', models.DateField()),
                ('starting_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('assignment_team', models.JSONField()),
                ('assignment_project_manager', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
