# Generated by Django 5.0.7 on 2024-09-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_project_manager',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assignment_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assignment_team',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assignment_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='creation_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='starting_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
