# Generated by Django 5.0.7 on 2024-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_Api', '0002_alter_assignments_assignment_project_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='creation_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='starting_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
