# Generated by Django 5.0.7 on 2024-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='', max_length=100)),
                ('employee_role', models.CharField(default='', max_length=50)),
                ('employee_email', models.EmailField(default='', max_length=100)),
                ('employee_contact', models.CharField(max_length=10)),
                ('employee_rating', models.FloatField(default=0, null=True)),
                ('active', models.BooleanField(default=1, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
