# Generated by Django 5.0.7 on 2024-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_rating',
            field=models.FloatField(default='0.0', null=True),
        ),
    ]
