# Generated by Django 5.0.7 on 2024-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0002_alter_employees_employee_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
