# Generated by Django 5.0.7 on 2024-08-23 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0003_employees_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 8, 21, 29, 520678, tzinfo=datetime.timezone.utc)),
        ),
        # migrations.AddField(
        #     model_name='employees',
        #     name='register_by_hr',
        #     field=models.BooleanField(default=''),
        # ),
    ]
