# Generated by Django 5.0.7 on 2024-08-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0004_employees_created_at_employees_register_by_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='created_at',
        ),
    ]
