# Generated by Django 5.0.7 on 2024-08-23 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0005_remove_employees_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 8, 22, 51, 732049, tzinfo=datetime.timezone.utc)),
        ),
    ]
