# Generated by Django 5.0.7 on 2024-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0007_alter_employees_created_at_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='employees',
        #     name='register_by_hr',
        #     field=models.BooleanField(default=False),
        # ),
    ]
