# Generated by Django 5.0.7 on 2024-08-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0008_alter_employees_register_by_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='register_by_hr',
            field=models.CharField(default='', max_length=20),
        ),
    ]
