# Generated by Django 5.0.7 on 2024-08-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0009_employees_register_by_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='register_by_hr',
            new_name='registered_by_hr',
        ),
    ]
