# Generated by Django 5.0.7 on 2024-08-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0011_alter_employees_created_at'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='employees',
        #     old_name='created_at',
        #     new_name='registered_on',
        # ),
    ]
