# Generated by Django 5.0.7 on 2024-08-27 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0012_rename_created_at_employees_registered_on'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='employees',
        #     name='created_at',
        # ),
        # migrations.AddField(
        #     model_name='employees',
        #     name='employee_registered_on',
        #     field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
    ]
