# Generated by Django 5.0.7 on 2024-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0013_remove_employees_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='created_at',
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_registered_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
