# Generated by Django 5.0.7 on 2024-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0014_remove_employees_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_registered_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_role',
            field=models.CharField(max_length=50),
        ),
    ]
