# Generated by Django 5.0.7 on 2024-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0015_alter_employees_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='registered_by_hr',
            field=models.CharField(max_length=20),
        ),
    ]
