# Generated by Django 5.0.7 on 2024-09-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_Api', '0016_alter_employees_registered_by_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='wip',
            field=models.IntegerField(default=0),
        ),
    ]
